#!/usr/bin/env bash
set -euo pipefail

repository_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repository_root"

candidate_directory="${1:-}"
if (( $# > 1 )); then
    echo "Usage: $0 [EXTRACTED_RELEASE_CANDIDATE_DIRECTORY]" >&2
    exit 2
fi

for command_name in cmp comm diff git jq lipo nm plutil python3 rg shasum stat swift tar unzip zipinfo; do
    command -v "$command_name" >/dev/null 2>&1 || {
        echo "Provider-neutral alias verification failed: missing $command_name" >&2
        exit 1
    }
done

fail() {
    echo "Provider-neutral alias verification failed: $*" >&2
    exit 1
}

sha256_file() {
    shasum -a 256 "$1" | awk '{print $1}'
}

provenance="ALIAS_SDK_PROVENANCE.json"
jq -e '.schemaVersion == 1' "$provenance" >/dev/null \
    || fail "unsupported provenance schema"
expected_source_commit="$(jq -er '.sourceCommit' "$provenance")"
expected_package_version="$(jq -er '.packageVersion' "$provenance")"
expected_schema_version="$(jq -er '.aliasReferenceSchemaVersion | tostring' "$provenance")"
[[ "$expected_source_commit" =~ ^[0-9a-f]{40}$ ]] \
    || fail "provenance source commit is not a full lowercase SHA"
[[ "$expected_package_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+-[0-9A-Za-z.-]+$ ]] \
    || fail "provenance package version is not a prerelease"

[[ "$(tr -d '[:space:]' <VERSION)" == "$expected_source_commit" ]] \
    || fail "VERSION does not identify the attested SDK source"
[[ "$(tr -d '[:space:]' <PACKAGE_VERSION)" == "$expected_package_version" ]] \
    || fail "PACKAGE_VERSION does not identify the release candidate"
[[ "$(tr -d '[:space:]' <ALIAS_REFERENCE_SCHEMA_VERSION)" == "$expected_schema_version" ]] \
    || fail "alias reference schema is not version 1"
grep -q 'GNU GENERAL PUBLIC LICENSE' LICENSE_GPL.txt \
    || fail "GPL license text is missing"

binary_path="BitwardenFFI.xcframework.zip"
expected_binary_bytes="$(jq -er '.binaryDistribution.bytes' "$provenance")"
expected_binary_sha256="$(jq -er '.binaryDistribution.sha256' "$provenance")"
[[ "$(stat -f '%z' "$binary_path")" == "$expected_binary_bytes" ]] \
    || fail "binary byte count does not match provenance"
[[ "$(sha256_file "$binary_path")" == "$expected_binary_sha256" ]] \
    || fail "binary SHA-256 does not match provenance"
(( expected_binary_bytes < 104857600 )) \
    || fail "binary exceeds the GitHub 100 MiB blob limit"

for generated_source in \
    Sources/BitwardenSdk/BitwardenAlias.swift \
    Sources/BitwardenSdk/BitwardenGenerators.swift \
    Sources/BitwardenSdk/BitwardenSDK.swift; do
    grep -q 'This file was autogenerated' "$generated_source" \
        || fail "$generated_source is not marked as generated"
done

for required_export in \
    'public protocol AliasProviderAdapter' \
    'open class AliasClient' \
    'public struct AliasIdentity' \
    'public enum AliasOperationPhase' \
    'public func createAliasReference' \
    'public func planAliasReconciliation' \
    'public struct EncryptionContext' \
    'encryptedByKeyId' \
    'public struct Repositories' \
    'openOrgInvite' \
    'aliasReference' \
    'public let partial: Bool'; do
    grep -R -q -F "$required_export" Sources/BitwardenSdk \
        || fail "missing public export: $required_export"
done

for forbidden_export in \
    AliasClientSettings \
    ForwarderServiceType \
    SimpleLogin \
    createCustomAlias \
    createRandomAlias \
    listCustomDomains \
    listMailboxes \
    providerIdentity; do
    if grep -R -q -F "$forbidden_export" Sources/BitwardenSdk; then
        fail "removed provider-specific export remains: $forbidden_export"
    fi
done

if grep -Eiq \
    '(alias[_-]?(api[_-]?key|access[_-]?token|credential|endpoint)|provider[_-]?instance|signed[_-]?suffix)' \
    Sources/BitwardenSdk/BitwardenAlias.swift; then
    fail "sensitive adapter configuration entered generated alias definitions"
fi

if find Sources BitwardenFFI.xcframework.zip -print \
    | grep -Eiq '(^|/)(commercial|bitwarden[_-]?license|license_sdk)(/|$)'; then
    fail "commercial-only path entered the public package"
fi
if rg -i -l \
    'CommercialPasswordManagerClient|CommercialVaultClient|PamClient|PAMClient|SecretsManagerClient|bitwarden[_-](commercial|license|pam|sm)' \
    Sources >/dev/null; then
    fail "commercial-only export entered generated sources"
fi

package_checksum="$(swift package compute-checksum "$binary_path")"
manifest_checksum="$(sed -nE 's/^[[:space:]]*checksum: "([0-9a-f]{64})".*/\1/p' Package.swift)"
[[ -n "$manifest_checksum" && "$package_checksum" == "$manifest_checksum" ]] \
    || fail "Package.swift checksum does not match $binary_path"

manifest_url="$(sed -nE 's/^[[:space:]]*url: "([^"]+)".*/\1/p' Package.swift)"
if [[ "$manifest_url" =~ ^https://raw\.githubusercontent\.com/mateoltd/sdk-swift/([0-9a-f]{40})/BitwardenFFI\.xcframework\.zip$ ]]; then
    distribution_commit="${BASH_REMATCH[1]}"
else
    fail "Package.swift binary URL is not pinned to an immutable sdk-swift commit"
fi
git cat-file -e "$distribution_commit^{commit}" 2>/dev/null \
    || fail "binary distribution commit is unavailable locally"
git merge-base --is-ancestor "$distribution_commit" HEAD \
    || fail "binary distribution commit is not an ancestor of the package head"
distribution_sha256="$(git show "$distribution_commit:$binary_path" | shasum -a 256 | awk '{print $1}')"
[[ "$distribution_sha256" == "$expected_binary_sha256" ]] \
    || fail "binary URL commit does not contain the verified archive"

swift package dump-package >/dev/null

# Verify the exact generated inputs and every distributed file, including FFI headers.
python3 - <<'PYVERIFY'
from pathlib import Path
import hashlib, json, zipfile
provenance = json.loads(Path("ALIAS_SDK_PROVENANCE.json").read_text())
expected_sources = provenance["generatedSourceHashes"]
actual_sources = {str(path): hashlib.sha256(path.read_bytes()).hexdigest()
                  for path in Path("Sources").rglob("*.swift")}
if actual_sources != expected_sources:
    raise SystemExit("Generated Swift/support source hashes differ from provenance")
with zipfile.ZipFile("BitwardenFFI.xcframework.zip") as archive:
    actual_entries = {name: hashlib.sha256(archive.read(name)).hexdigest()
                      for name in archive.namelist()}
if actual_entries != provenance["binaryDistribution"]["entrySha256"]:
    raise SystemExit("Distributed library/header hashes differ from provenance")
PYVERIFY

temporary_directory="$(mktemp -d "${TMPDIR:-/tmp}/bitwarden-alias-verify.XXXXXX")"
trap 'rm -rf "$temporary_directory"' EXIT
unzip -q "$binary_path" -d "$temporary_directory" -x '*/libbitwarden_uniffi.a'
xcframework="$temporary_directory/BitwardenFFI.xcframework"
[[ -d "$xcframework" ]] || fail "archive does not contain BitwardenFFI.xcframework"

unzip -Z1 "$binary_path" >"$temporary_directory/archive-order.txt"
LC_ALL=C sort "$temporary_directory/archive-order.txt" \
    >"$temporary_directory/archive-order.sorted.txt"
cmp -s "$temporary_directory/archive-order.txt" "$temporary_directory/archive-order.sorted.txt" \
    || fail "XCFramework ZIP entries are not deterministically ordered"
if zipinfo -l "$binary_path" \
    | sed '1,2d;$d' \
    | awk '$1 != "-rw-r--r--" || $8 != "80-Jan-01" || $9 != "00:00" { exit 1 }'; then
    :
else
    fail "XCFramework ZIP permissions or timestamps are not canonical"
fi
if unzip -Z1 "$binary_path" | grep -Eq '(^|/)(\.DS_Store|__MACOSX)(/|$)'; then
    fail "archive contains Apple metadata"
fi

mapfile="$temporary_directory/libraries.txt"
plutil -convert json -o - "$xcframework/Info.plist" \
    | jq -r '.AvailableLibraries[] | [
        .LibraryIdentifier,
        .SupportedPlatform,
        (.SupportedPlatformVariant // "device"),
        (.SupportedArchitectures | join(","))
    ] | @tsv' >"$mapfile"
expected_libraries="$temporary_directory/expected-libraries.txt"
printf '%s\n' \
    $'ios-arm64\tios\tdevice\tarm64' \
    $'ios-arm64-simulator\tios\tsimulator\tarm64' \
    >"$expected_libraries"
cmp -s "$expected_libraries" "$mapfile" \
    || fail "XCFramework slices or canonical plist ordering changed"

expected_symbols="$temporary_directory/expected-alias-symbols.txt"
rg -o '[a-z]+_bitwarden_alias_[A-Za-z0-9_]+' Sources/BitwardenSdk/BitwardenAlias.swift \
    | LC_ALL=C sort -u >"$expected_symbols"
[[ "$(wc -l <"$expected_symbols" | tr -d '[:space:]')" -ge 50 ]] \
    || fail "generated Swift alias ABI reference set is unexpectedly small"

expected_all_symbols="$temporary_directory/expected-all-symbols.txt"
rg --no-filename -o '(ffi|uniffi)_bitwarden_[A-Za-z0-9_]+' Sources/BitwardenSdk \
    | LC_ALL=C sort -u >"$expected_all_symbols"

for library_directory in ios-arm64 ios-arm64-simulator; do
    header="$xcframework/$library_directory/Headers/BitwardenAliasFFI.h"
    library="$temporary_directory/$library_directory-libbitwarden_uniffi.a"
    header_symbols="$temporary_directory/$library_directory-header-symbols.txt"
    binary_symbols="$temporary_directory/$library_directory-binary-symbols.txt"
    missing_symbols="$temporary_directory/$library_directory-missing-symbols.txt"

    rg -o '[a-z]+_bitwarden_alias_[A-Za-z0-9_]+' "$header" \
        | LC_ALL=C sort -u >"$header_symbols"
    comm -23 "$expected_symbols" "$header_symbols" >"$missing_symbols"
    [[ ! -s "$missing_symbols" ]] || {
        sed 's/^/missing header symbol: /' "$missing_symbols" >&2
        fail "$library_directory alias header does not satisfy generated Swift"
    }

    unzip -p "$binary_path" \
        "BitwardenFFI.xcframework/$library_directory/libbitwarden_uniffi.a" >"$library"
    [[ "$(lipo -archs "$library")" == "arm64" ]] \
        || fail "$library_directory library is not arm64-only"
    nm --no-llvm-bc -gU "$library" | awk '{print $NF}' | sed 's/^_//' | LC_ALL=C sort -u \
        >"$binary_symbols"
    comm -23 "$expected_symbols" "$binary_symbols" >"$missing_symbols"
    [[ ! -s "$missing_symbols" ]] || {
        sed 's/^/missing binary symbol: /' "$missing_symbols" >&2
        fail "$library_directory native library does not satisfy generated Swift"
    }
    rg --no-filename -o '(ffi|uniffi)_bitwarden_[A-Za-z0-9_]+' \
        "$xcframework/$library_directory/Headers" \
        | LC_ALL=C sort -u >"$header_symbols"
    for symbol_set in "$header_symbols" "$binary_symbols"; do
        comm -23 "$expected_all_symbols" "$symbol_set" >"$missing_symbols"
        [[ ! -s "$missing_symbols" ]] || {
            cat "$missing_symbols" >&2
            fail "$library_directory does not satisfy the complete generated Swift ABI ($symbol_set)"
        }
    done
    echo "$library_directory: verified $(wc -l <"$expected_all_symbols" | tr -d '[:space:]') generated ABI symbols"
    find "$library" -delete
done

if [[ -n "$candidate_directory" ]]; then
    [[ -d "$candidate_directory" ]] || fail "release candidate directory is missing"
    candidate_directory="$(cd "$candidate_directory" && pwd)"
    candidate_manifest="$candidate_directory/handoff-manifest.json"
    candidate_checksums="$candidate_directory/SHA256SUMS"
    candidate_sbom="$candidate_directory/SBOM.cdx.json"
    [[ -f "$candidate_manifest" && -f "$candidate_checksums" && -f "$candidate_sbom" ]] \
        || fail "release candidate evidence bundle is incomplete"

    (
        cd "$candidate_directory"
        shasum -a 256 -c SHA256SUMS >/dev/null
    ) || fail "release candidate checksum index failed"

    [[ "$(jq -er '.sourceCommit' "$candidate_manifest")" == "$expected_source_commit" ]] \
        || fail "release candidate source commit differs from public provenance"
    [[ "$(jq -er '.releaseVersion' "$candidate_manifest")" == "$expected_package_version" ]] \
        || fail "release candidate version differs from public provenance"
    [[ "$(jq -er '.aliasReferenceSchemaVersion | tostring' "$candidate_manifest")" == \
        "$expected_schema_version" ]] \
        || fail "release candidate schema differs from public provenance"

    swift_artifact_relative="$(jq -er '.packages.swift.artifact.path' "$candidate_manifest")"
    swift_artifact="$candidate_directory/$swift_artifact_relative"
    [[ -f "$swift_artifact" ]] || fail "release candidate Swift archive is missing"
    [[ "$(sha256_file "$swift_artifact")" == \
        "$(jq -er '.packages.swift.artifact.sha256' "$candidate_manifest")" ]] \
        || fail "release candidate Swift archive hash differs from its manifest"
    [[ "$(stat -f '%z' "$swift_artifact")" == \
        "$(jq -er '.packages.swift.artifact.bytes' "$candidate_manifest")" ]] \
        || fail "release candidate Swift archive size differs from its manifest"

    [[ "$(sha256_file "$swift_artifact")" == \
        "$(jq -er '.verifiedEvidence.swiftArchiveSha256' "$provenance")" ]] \
        || fail "Swift archive hash differs from public provenance"
    [[ "$(sha256_file "$candidate_checksums")" == \
        "$(jq -er '.verifiedEvidence.checksumIndexSha256' "$provenance")" ]] \
        || fail "candidate checksum index differs from public provenance"
    [[ "$(sha256_file "$candidate_manifest")" == \
        "$(jq -er '.verifiedEvidence.handoffManifestSha256' "$provenance")" ]] \
        || fail "handoff manifest differs from public provenance"
    [[ "$(sha256_file "$candidate_sbom")" == \
        "$(jq -er '.verifiedEvidence.cycloneDxSbomSha256' "$provenance")" ]] \
        || fail "SBOM differs from public provenance"
    candidate_sigstore="$candidate_directory/PROVENANCE.sigstore.json"
    [[ -f "$candidate_sigstore" ]] || fail "candidate Sigstore bundle is missing"
    [[ "$(sha256_file "$candidate_sigstore")" == \
        "$(jq -er '.verifiedEvidence.sigstoreBundleSha256' "$provenance")" ]] \
        || fail "Sigstore bundle differs from public provenance"

    swift_api_relative="$(jq -er '.evidence.apiReports["alias-sdk-swift"].path' "$candidate_manifest")"
    audit_relative="$(jq -er '.evidence.dependencyAudit.path' "$candidate_manifest")"
    [[ "$(sha256_file "$candidate_directory/$swift_api_relative")" == \
        "$(jq -er '.verifiedEvidence.swiftApiReportSha256' "$provenance")" ]] \
        || fail "Swift API report differs from public provenance"
    [[ "$(sha256_file "$candidate_directory/$audit_relative")" == \
        "$(jq -er '.verifiedEvidence.auditReportSha256' "$provenance")" ]] \
        || fail "dependency audit report differs from public provenance"
    jq -e \
        '.cargo.unacceptedVulnerabilityCount == 0 and .npm.vulnerabilities.total == 0' \
        "$candidate_directory/$audit_relative" >/dev/null \
        || fail "candidate dependency audit has unaccepted findings"
    jq -e '.bomFormat == "CycloneDX" and .specVersion == "1.6"' "$candidate_sbom" >/dev/null \
        || fail "candidate SBOM is not CycloneDX 1.6"

    candidate_package="$temporary_directory/candidate-package"
    mkdir "$candidate_package"
    tar -xzf "$swift_artifact" -C "$candidate_package"
    [[ "$(tr -d '[:space:]' <"$candidate_package/VERSION")" == "$expected_source_commit" ]] \
        || fail "Swift archive VERSION differs from candidate source"
    [[ "$(tr -d '[:space:]' <"$candidate_package/PACKAGE_VERSION")" == \
        "$expected_package_version" ]] \
        || fail "Swift archive package version differs from candidate"
    diff -qr "$candidate_package/Sources" Sources >/dev/null \
        || fail "public generated sources differ from the attested Swift archive"
    cmp -s "$candidate_package/LICENSE_GPL.txt" LICENSE_GPL.txt \
        || fail "public GPL license differs from the attested Swift archive"

    "$repository_root/scripts/create-xcframework-zip.sh" \
        "$candidate_package/BitwardenFFI.xcframework" \
        "$temporary_directory/repacked-first.zip" >/dev/null
    "$repository_root/scripts/create-xcframework-zip.sh" \
        "$candidate_package/BitwardenFFI.xcframework" \
        "$temporary_directory/repacked-second.zip" >/dev/null
    cmp -s "$temporary_directory/repacked-first.zip" "$temporary_directory/repacked-second.zip" \
        || fail "downstream XCFramework packaging is not reproducible"
    cmp -s "$temporary_directory/repacked-first.zip" "$binary_path" \
        || fail "committed XCFramework archive is not the reproducible candidate transform"
fi

echo "Provider-neutral alias provenance, package, ABI, boundary, checksum, and slices passed"
