#!/usr/bin/env bash
set -euo pipefail

repository_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repository_root"

fail() {
    echo "Provider-neutral alias verification failed: $*" >&2
    exit 1
}

expected_source_commit="99c33ed26e51421224a4daecdf838057f1d66e75"
expected_package_version="0.3.0-alias-provider-neutral.1"
expected_schema_version="1"

[[ "$(tr -d '[:space:]' <VERSION)" == "$expected_source_commit" ]] \
    || fail "VERSION does not identify the attested SDK source"
[[ "$(tr -d '[:space:]' <PACKAGE_VERSION)" == "$expected_package_version" ]] \
    || fail "PACKAGE_VERSION does not identify the release candidate"
[[ "$(tr -d '[:space:]' <ALIAS_REFERENCE_SCHEMA_VERSION)" == "$expected_schema_version" ]] \
    || fail "alias reference schema is not version 1"
grep -q 'GNU GENERAL PUBLIC LICENSE' LICENSE_GPL.txt \
    || fail "GPL license text is missing"

for generated_source in \
    Sources/BitwardenSdk/BitwardenAlias.swift \
    Sources/BitwardenSdk/BitwardenGenerators.swift \
    Sources/BitwardenSdk/BitwardenSDK.swift; do
    grep -q 'This file was autogenerated' "$generated_source" \
        || fail "$generated_source is not marked as generated"
done

for required_export in \
    'public protocol AliasProviderAdapter' \
    'open class AliasClient' \
    'public struct AliasIdentity' \
    'public enum AliasOperationPhase' \
    'public func createAliasReference' \
    'public func planAliasReconciliation'; do
    grep -R -q -F "$required_export" Sources/BitwardenSdk \
        || fail "missing public export: $required_export"
done

for forbidden_export in \
    AliasClientSettings \
    ForwarderServiceType \
    SimpleLogin \
    createCustomAlias \
    createRandomAlias \
    listCustomDomains \
    listMailboxes \
    providerIdentity; do
    if grep -R -q -F "$forbidden_export" Sources/BitwardenSdk; then
        fail "removed provider-specific export remains: $forbidden_export"
    fi
done

if grep -Eiq \
    '(alias[_-]?(api[_-]?key|access[_-]?token|credential|endpoint)|provider[_-]?instance|signed[_-]?suffix)' \
    Sources/BitwardenSdk/BitwardenAlias.swift; then
    fail "sensitive adapter configuration entered generated alias definitions"
fi

package_checksum="$(swift package compute-checksum BitwardenFFI.xcframework.zip)"
manifest_checksum="$(sed -nE 's/^[[:space:]]*checksum: "([0-9a-f]{64})".*/\1/p' Package.swift)"
[[ -n "$manifest_checksum" && "$package_checksum" == "$manifest_checksum" ]] \
    || fail "Package.swift checksum does not match BitwardenFFI.xcframework.zip"

temporary_directory="$(mktemp -d "${TMPDIR:-/tmp}/bitwarden-alias-verify.XXXXXX")"
trap 'rm -rf "$temporary_directory"' EXIT
unzip -q BitwardenFFI.xcframework.zip -d "$temporary_directory"
xcframework="$temporary_directory/BitwardenFFI.xcframework"
[[ -d "$xcframework" ]] || fail "archive does not contain BitwardenFFI.xcframework"

mapfile="$temporary_directory/libraries.txt"
plutil -convert json -o - "$xcframework/Info.plist" \
    | jq -r '.AvailableLibraries[] | [
        .LibraryIdentifier,
        .SupportedPlatform,
        (.SupportedPlatformVariant // "device"),
        (.SupportedArchitectures | join(","))
    ] | @tsv' >"$mapfile"
expected_libraries="$temporary_directory/expected-libraries.txt"
printf '%s\n' \
    $'ios-arm64\tios\tdevice\tarm64' \
    $'ios-arm64-simulator\tios\tsimulator\tarm64' \
    >"$expected_libraries"
cmp -s "$expected_libraries" "$mapfile" \
    || fail "XCFramework slices or canonical plist ordering changed"

[[ "$(lipo -archs "$xcframework/ios-arm64/libbitwarden_uniffi.a")" == "arm64" ]] \
    || fail "device library is not arm64-only"
[[ "$(lipo -archs "$xcframework/ios-arm64-simulator/libbitwarden_uniffi.a")" == "arm64" ]] \
    || fail "simulator library is not arm64-only"

if find "$temporary_directory" -name .DS_Store -o -name __MACOSX | grep -q .; then
    fail "archive contains Apple metadata"
fi

echo "Provider-neutral alias package metadata, API boundary, checksum, and slices passed"
